### ISSUE TITLE
Error: [$injector:modulerr] Failed to instantiate module mean.system due to:

### ISSUE THREAD

**Issue by EwanValentine** [linnovate/mean#952] opened 2014-12-09 11:14 UTC
```Uncaught Error: [$injector:modulerr] Failed to instantiate module mean due to:
Error: [$injector:modulerr] Failed to instantiate module mean.system due to:
Error: [$injector:modulerr] Failed to instantiate module mean-factory-interceptor due to:
Error: [$injector:nomod] Module 'mean-factory-interceptor' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.```

I seem to get this issue intermittently. If I go into ```/packages/users/public/users.js``` and remove ```['mean.system']``` from the DI it will work for a while, then I'll get the same error and putting that line back in seems to fix it again... really weird. 

Any help appreciated, cheers!

**Comment by rmisiak** [comment] 2015-01-05 11:35
I'm still experiencing this issue as of Jan 5th.

**Comment by coolsebz** [comment] 2015-01-06 08:25
i can confirm, i have this issue too, though for me it's very random as to when it occurs (tried with aggregate true and false)

And when it does i have to restart grunt a couple of times before i can use the web-app again

**Comment by spelley** [comment] 2015-01-14 14:30
I`m having a similar issue; have to reboot grunt multiple times in order for it to work (mine is erroring out on .theme) and switching aggregation has no effect as far as I can tell

**Comment by rick4470** [comment] 2015-01-31 08:15
Same issue here, from looking at the code it looks like it's a timing issue.

**Comment by liorkesos** [comment] 2015-01-31 08:17
Please send the output of the mean status command.

**Comment by rick4470** [comment] 2015-01-31 08:19
```javascript
 Object {definePalette: function, extendPalette: function, theme: function, setDefaultTheme: function, alwaysWatchTheme: function…}
aggregated.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module mean due to:
Error: [$injector:modulerr] Failed to instantiate module mean.system due to:
TypeError: undefined is not a function
    at http://192.168.56.101:3000/modules/aggregated.js:32685:1408
    at Object.invoke (http://192.168.56.101:3000/modules/aggregated.js:4187:17)
    at runInvokeQueue (http://192.168.56.101:3000/modules/aggregated.js:4093:35)
    at http://192.168.56.101:3000/modules/aggregated.js:4102:11
    at forEach (http://192.168.56.101:3000/modules/aggregated.js:328:20)
    at loadModules (http://192.168.56.101:3000/modules/aggregated.js:4083:5)
    at http://192.168.56.101:3000/modules/aggregated.js:4100:40
    at forEach (http://192.168.56.101:3000/modules/aggregated.js:328:20)
    at loadModules (http://192.168.56.101:3000/modules/aggregated.js:4083:5)
    at createInjector (http://192.168.56.101:3000/modules/aggregated.js:4009:11)
http://errors.angularjs.org/1.3.11/$injector/modulerr?p0=mean.system&p1=Typ…0(http%3A%2F%2F192.168.56.101%3A3000%2Fmodules%2Faggregated.js%3A4009%3A11)
    at REGEX_STRING_REGEXP (http://192.168.56.101:3000/modules/aggregated.js:68:12)
    at http://192.168.56.101:3000/modules/aggregated.js:4122:15
    at forEach (http://192.168.56.101:3000/modules/aggregated.js:328:20)
    at loadModules (http://192.168.56.101:3000/modules/aggregated.js:4083:5)
    at http://192.168.56.101:3000/modules/aggregated.js:4100:40
    at forEach (http://192.168.56.101:3000/modules/aggregated.js:328:20)
    at loadModules (http://192.168.56.101:3000/modules/aggregated.js:4083:5)
    at createInjector (http://192.168.56.101:3000/modules/aggregated.js:4009:11)
    at doBootstrap (http://192.168.56.101:3000/modules/aggregated.js:1451:20)
    at Object.bootstrap (http://192.168.56.101:3000/modules/aggregated.js:1472:12)
http://errors.angularjs.org/1.3.11/$injector/modulerr?p0=mean&p1=Error%3A%2…0(http%3A%2F%2F192.168.56.101%3A3000%2Fmodules%2Faggregated.js%3A1472%3A12)
angular-resource.min.js.map:1 GET http://192.168.56.101:3000/modules/angular-resource.min.js.map 404 (Not Found)
```

**Comment by rick4470** [comment] 2015-01-31 08:25
```bash
➜  learnMean git:(master) ✗ mean status

    MEAN Status
    -----------

    MEAN VERSION: 0.4.3

    DB connection successful!

    MongoDB URI: mongodb://localhost/mean-dev

    checking meanio and global mean-cli versions

/usr/local/lib/node_modules/mean-cli/node_modules/npm/node_modules/read-installed/read-installed.js:362
  Object.keys(deps).forEach(function (d) {
         ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at unmarkExtraneous (/usr/local/lib/node_modules/mean-cli/node_modules/npm/node_modules/read-installed/read-installed.js:362:10)
    at /usr/local/lib/node_modules/mean-cli/node_modules/npm/node_modules/read-installed/read-installed.js:137:5
    at next (/usr/local/lib/node_modules/mean-cli/node_modules/npm/node_modules/read-installed/read-installed.js:185:14)
    at /usr/local/lib/node_modules/mean-cli/node_modules/npm/node_modules/read-installed/read-installed.js:169:14
    at Object.oncomplete (evalmachine.<anonymous>:107:15)
```

**Comment by rick4470** [comment] 2015-01-31 08:55
Ahh! I was actually trying to call a function that did not exist.

**Comment by camhart** [comment] 2015-02-12 20:57
I too am having problems with this.  Changing aggregate to true made no difference.  Mine never works though.

**Comment by rmisiak** [comment] 2015-02-27 00:17
Does this issue still exist?  I implemented a local workaround by manually including all assets but would like to go back to the platform version if the issue is resolved.

**Comment by liorkesos** [comment] 2015-02-27 04:11
,I think this was resolved in 0.4.3

**Comment by camhart** [comment] 2015-02-27 04:21
I can confirm that this still is a bug (in version 0.4.3).

I spoke with MilosStanic about it (not sure if he's on your team or not).
https://gitter.im/linnovate/mean/archives/2015/02/11

**Comment by ramandv** [comment] 2015-02-27 17:34
I have the same issue too. I just updated my code with
```
$ git pull upstream master
$ npm install
```
after that I am facing this error. 

None of the above solution work though. Do I need to do anything special?

**Comment by liorkesos** [comment] 2015-02-27 18:00
Please run mean status and send the mean version, meanio version and CLI
version..

**Comment by ramandv** [comment] 2015-02-28 00:35
```
➜  builtwith git:(master) ✗ mean status

    MEAN Status
    -----------

    MEAN VERSION: 0.4.3

    DB connection successful!

    MongoDB URI: mongodb://localhost/mean-dev

    checking meanio and global mean-cli versions
    meanio at latest version: 0.7.1
    mean-cli at latest version: 0.9.14
```

**Comment by ramandv** [comment] 2015-02-28 07:25
Figured out the problem, the problem was my custom app route was also having route state called "home". it was interfering with system app "home" route state. 

Is there any better way to identify this issue?

**Comment by max-mog** [comment] 2015-04-12 03:15
@ramandv You just saved me so much time, I was frustrated by this error.
It was indeed some conflict in my rouding. I had duplicates.

I do agree that the error is very mis-leading ...



Cheers.

**Comment by liorkesos** [comment] 2015-04-12 06:23
Thanks guys,
This is very informative - we'll try to build in some way to identify and
have a better error communicated.
Lior

On Sun, Apr 12, 2015 at 6:15 AM, max-mog <notifications@github.com> wrote:

> @ramandv <https://github.com/ramandv> You just saved me so much time, I
> was frustrated by this error.
> It was indeed some conflict in my rouding. I had duplicates.
>
> I do agree that the error is very mis-leading ...
>
> Cheers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/952#issuecomment-91976779>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by max-mog** [comment] 2015-04-12 06:25
Thanks Lior, that would be very helpful.
Cheers,
Max

**Comment by saeed68gm** [comment] 2016-03-29 18:18
I'm on the latest version of mean and occasionally run into this problem. But when I run into it restarting gulp does not help.

**Comment by saeed68gm** [comment] 2016-03-30 04:24
Now it is 100% reproducible, not sure how to resolve this. 

Here is the error output:

`
(anonymous function)	@	angular.js:38
(anonymous function)	@	angular.js:4547
q	@	angular.js:321
g	@	angular.js:4508
eb	@	angular.js:4430
c	@	angular.js:1710
yc	@	angular.js:1731
(anonymous function)	@	index.js?v=2738ecb…:9
i	@	jquery.min.js?v=1d35678…:2
j.fireWith	@	jquery.min.js?v=1d35678…:2
n.extend.ready	@	jquery.min.js?v=1d35678…:2
J	@	jquery.min.js?v=1d35678…:2
`
and the mean status:

`
(anonymous function)	@	angular.js:38
(anonymous function)	@	angular.js:4547
q	@	angular.js:321
g	@	angular.js:4508
eb	@	angular.js:4430
c	@	angular.js:1710
yc	@	angular.js:1731
(anonymous function)	@	index.js?v=2738ecb…:9
i	@	jquery.min.js?v=1d35678…:2
j.fireWith	@	jquery.min.js?v=1d35678…:2
n.extend.ready	@	jquery.min.js?v=1d35678…:2
J	@	jquery.min.js?v=1d35678…:2
`

**Comment by timelf123** [comment] 2016-03-30 17:24
Make sure you have all bower deps installed:
`mean postinstall` or `npm run postinstall`

**Comment by saeed68gm** [comment] 2016-03-31 02:14
@timelf123  Thanks for your reply. I should have everything installed, just confirmed by clearing cache and reinstalling everything. The thing is the app was working fine (only occasionally displaying this behavior, not sure why).

After I tried to deploy in production environment and made a few minor changes this started happening and now it is completely unusable. I did not add any new packages as result of my change....any help is appreciated

**Comment by joejean** [comment] 2016-04-20 20:54
I'm facing the same issue and running ```npm run postinstall``` still does not fix the issue. Anyone knows another solution? Thanks

**Comment by joejean** [comment] 2016-04-20 21:19
I found the solution changing ```"angular-ui-router": "#master"```, to ```"angular-ui-router": "latest" ``` in bower.json fixed the issue.That fix was suggested [here](https://github.com/linnovate/mean/issues/1492) by @ilyachenko

**Comment by snu-ceyda** [comment] 2016-04-25 11:14
Had the same problem changing the bower.json as mentioned above fixed it. Thanks @joejean

**Comment by rivkabenshalom** [comment] 2016-06-30 07:51
change "angular-ui-router": "#master", to "angular-ui-router": "latest" in bower.json.
(before delete bower directories)

**Comment by clayjones94** [comment] 2016-07-28 16:08
`  Error: [$injector:modulerr] Failed to instantiate module mean due to:
  [$injector:modulerr] Failed to instantiate module mean.meanStarter due to:
  [$injector:modulerr] Failed to instantiate module mean.system due to:
  NETWORK_ERR: XMLHttpRequest Exception 101
  send@[native code]
  MeanConfigProvider@app.js:65470:18
  app.js:65477:33
  [native code]
  instantiate@app.js:15396:62
  provider@app.js:15210:48
  app.js:15202:25
  runInvokeQueue@app.js:15274:41
  app.js:15282:26
  forEach@app.js:10984:25
  loadModules@app.js:15264:13
  app.js:15281:52
  forEach@app.js:10984:25
  loadModules@app.js:15264:13
  app.js:15281:52
  forEach@app.js:10984:25
  loadModules@app.js:15264:13
  createInjector@app.js:15186:31
  doBootstrap@app.js:12421:35
  bootstrap@app.js:12442:24
  app.js:86:23
  trigger@app.js:13870:10
  defaultHandlerWrapper@app.js:14160:16
  eventHandler@app.js:14148:24`

I am getting this error and I've tried re-downloading performing the command line above but still nothing.

**Comment by VikramTiwari** [comment] 2016-09-17 04:19
Wow! I am amazed how this error keeps popping up. This should be working fine now. Reopen if it pops his head back again. 📟

**Closed by VikramTiwari** 2016-09-17 04:19 UTC
Labels: documentation

**Comment by angry-birdman** [comment] 2016-10-14 04:47
Hi, I am still setting the error and I've tried the solutions above but none of them worked...
> angular.js:68Uncaught Error: [$injector:modulerr] Failed to instantiate module mean due to:
Error: [$injector:modulerr] Failed to instantiate module mean.meanStarter due to:
Error: State 'home' is already defined
    at registerState (http://localhost:3000/bundle/app.js:51835:45)
    at $StateProvider.state (http://localhost:3000/bundle/app.js:52345:6)
    at MeanStateProvider.state (http://localhost:3000/bundle/app.js:96118:23)
    at http://localhost:3000/bundle/app.js:92558:23
    at Object.invoke (http://localhost:3000/bundle/app.js:15500:20)
    at runInvokeQueue (http://localhost:3000/bundle/app.js:15393:36)
    at http://localhost:3000/bundle/app.js:15402:12
    at forEach (http://localhost:3000/bundle/app.js:11103:21)
    at loadModules (http://localhost:3000/bundle/app.js:15383:6)
    at http://localhost:3000/bundle/app.js:15400:41
http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=mean.meanStarter&p1…%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Fbundle%2Fapp.js%3A15400%3A41
    at http://localhost:3000/bundle/app.js:10850:13
    at http://localhost:3000/bundle/app.js:15422:16
    at forEach (http://localhost:3000/bundle/app.js:11103:21)
    at loadModules (http://localhost:3000/bundle/app.js:15383:6)
    at http://localhost:3000/bundle/app.js:15400:41
    at forEach (http://localhost:3000/bundle/app.js:11103:21)
    at loadModules (http://localhost:3000/bundle/app.js:15383:6)
    at createInjector (http://localhost:3000/bundle/app.js:15305:20)
    at doBootstrap (http://localhost:3000/bundle/app.js:12540:21)
    at Object.bootstrap (http://localhost:3000/bundle/app.js:12561:13)
http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=mean&p1=Error%3A%20….bootstrap%20(http%3A%2F%2Flocalhost%3A3000%2Fbundle%2Fapp.js%3A12561%3A13)
