### ISSUE TITLE
Gotta be something simple.

### ISSUE THREAD

**Issue by kazajhodo** [linnovate/mean#1532] opened 2016-04-19 21:11 UTC
I built out an entire huge application with mean.io, now i've upgraded and have been having issues getting it working.

In order to resolve the issue, I started over with a clean mean.io install, unchanged. Clean node install, upgraded mongo so on so on.

I've tried changing ports and databases. This did work as far as hitting the different ports, but no different in regards to function.

All I'm getting on the front-end is localhost didn't send any data.
![screen shot 2016-04-19 at 1 41 28 pm](https://cloud.githubusercontent.com/assets/1173204/14651190/758f2856-0634-11e6-8902-7b71d4c9a327.png)

In the console of node, 
![screen shot 2016-04-19 at 1 42 40 pm](https://cloud.githubusercontent.com/assets/1173204/14651224/a218ce72-0634-11e6-9295-929eafc9ccec.png)

I'm starting to literally trace through the code, I don't have any errors... everything is bone stock to the master branch. Any enlightenment would be fantastic.

I'll just keep tracing through the code to see if I can figure it out, but it seems to be failing before the application is even hit at this point.

GET / - - - - ms

The best I've gotten. Any ideas? Again, bone stock master branch.

OSX Capitan 10.11.4

Node 4.4.3
Mongo 3.2.4
Git 1.9.5
Mean 0.6.1
Mean Cli 0.11.1
Meanio 0.9.1

According to mean status my database connection is successful.

Any ideas would be great.

**Comment by Manish2005** [comment] 2016-04-21 18:36
I am facing similar issue.. After fresh mean.io install, the app is not loading. There is no error in console

**Comment by pashist** [comment] 2016-04-21 18:50
could you try to run with Node 5.x ?

**Comment by Manish2005** [comment] 2016-04-21 19:13
@pashist , I installed Node 5.10 as you suggested, but no use.
It's still the same,

As you can see in the screenshot, there is no error in the console

![nodeissue](https://cloud.githubusercontent.com/assets/3137897/14721260/27a5688a-0823-11e6-86b3-628fc448686a.PNG)

**Comment by kazajhodo** [comment] 2016-04-21 21:23
I did a few things here to resolve the issue in my case. First off my application was running off of an older version of mean io.

I pulled a fresh 0.5.5 I think it was, this is similar to my old install.

Then I changed in the root bower.json file, "angular-ui-router" value to 'latest'. 
"angular-ui-router": "latest"

This resolved my front-end angular issue locally.

This is with:
Node 4.4.3
Mongo 3.2.4
Git 1.9.5
Mean 0.6.1
Mean Cli 0.11.1
Meanio 0.9.1

As stated in the original post.

This resolved the issue as far my application was concerned, though its important to note that I am no longer in the master branch.

Although in the master version, I received the same out put as @Manish2005  mentions above in his screenshot. I never did resolve that, but perhaps the issues are related if someone wants to give the small adjustment a shot.

**Comment by Manish2005** [comment] 2016-05-17 11:15
Is anybody even looking into this issue? This is a show stopper. And for people like us who do not know Mean.io in and out, the only option is to ask for help.

This issue has been open for almost a month now. I am sorry to say but things don't look too good for mean.io. Multiple users have reported this issue. 
We are left with no other choice but to look for other options.

It looks like the contributors too aren't too interested in mean.io now

**Comment by Manish2005** [comment] 2016-05-17 11:17
How is one supposed to use it when they cannot get it's fresh install to work?

**Comment by pashist** [comment] 2016-05-17 12:57
@Manish2005 unfortunately i cant reproduce this error, tried on ubuntu 14 and windows 10 and all work fine.
Try to use mean-cli last version, it was recently updated, and install mean by running `mean init`.
If it not help, publish your config, i ll try to install and run mean in same environment

**Comment by timelf123** [comment] 2016-05-17 17:07
Sometimes this happens when there are bad NPM package installs. This will fail silently and causes the dreaded

`GET / - - - - ms`

**Comment by Manish2005** [comment] 2016-05-17 18:33
@pashist As you said, I tried updating to latest mean-cli version and created a new project.. but its still the same.

Here's my config for your reference - 

Node - 5.10.1
NPM - 3.8.5
MEAN : 1.0.0
MEAN-CLI - 0.12.10

Any help appreciated :)

**Comment by pashist** [comment] 2016-05-17 19:12
@Manish2005 what operating system you use?

**Comment by Manish2005** [comment] 2016-05-17 19:15
@pashist  I am using Windows 10, previous installation of mean.io is working fine.
I have a project developed with previous version. but for a new project when I am trying to checkout a fresh copy I am facing this issue.

**Comment by timelf123** [comment] 2016-05-17 19:24
If you clone this repo and run npm install, instead of using the mean-cli, do you get the same result?

**Comment by Manish2005** [comment] 2016-05-19 12:46
@timelf123 Cloning actually worked. 
I updated windows build SDK version and then cloned this repo and then did `npm install`. And it worked.

So I thought may be it was issue with the Windows Build SDK.. so I tried `mean init` again on a new project.. but no use. It's still the same.

**Comment by timelf123** [comment] 2016-05-20 18:29
Closing as resolved. Please open a new issue in linnovate/mean-cli if you still have issues with the CLI scaffolding

**Closed by timelf123** 2016-05-20 18:29 UTC
