### ISSUE TITLE
Cannot destructure property `createHash` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by intergleam** [linnovate/mean#1914] opened 2018-10-25 07:35 UTC
```
osboxes@osboxes:~/pr/mean$ ng build --watch
Your global Angular CLI version (7.0.3) is greater than your local
version (6.2.6). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Cannot destructure property `createHash` of 'undefined' or 'null'.
TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.
    at Object.<anonymous> (/home/osboxes/pr/mean/node_modules/mini-css-extract-plugin/dist/index.js:21:5)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/osboxes/pr/mean/node_modules/mini-css-extract-plugin/dist/cjs.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)

```

**Comment by feenr** [comment] 2018-10-25 20:22
This is a duplicate of https://github.com/linnovate/mean/issues/1911

**Closed** 2018-10-31 06:29 UTC
