### ISSUE TITLE
unable to run project, Kindly help

### ISSUE THREAD

**Issue by renceabishek** [linnovate/mean#1908] opened 2018-10-04 16:09 UTC
I'm getting below issue after i clone and do npm install & npm start

 ERR! code ELIFECYCLE
 ERR! errno 1
 ERR! mean@0.0.0 start: `concurrently -c 'yellow.bold,green.bold' -n 'SERVER,BUILD' 'nodemon server' '
build --watch'`
 ERR! Exit status 1
 ERR!
 ERR! Failed at the mean@0.0.0 start script.
 ERR! This is probably not a problem with npm. There is likely additional logging output above.

 ERR! A complete log of this run can be found in:
 ERR!     C:\Users\Renceabishek\AppData\Roaming\npm-cache\_logs\2018-10-04T16_02_31_271Z-debug.log

**Comment by feenr** [comment] 2018-10-07 15:52
I'm also not able to install and start the app after a fresh clone.

```
[SERVER] [nodemon] 1.18.4
[SERVER] [nodemon] to restart at any time, enter `rs`
[SERVER] [nodemon] watching: *.*
[SERVER] [nodemon] starting `node server`
[SERVER] /Users/feenr/workspaces/mean/server/config/config.js:30
[SERVER]   throw new Error(`Config validation error: ${error.message}`);
[SERVER]   ^
[SERVER] 
[SERVER] Error: Config validation error: child "JWT_SECRET" fails because ["JWT_SECRET" is required]
[SERVER]     at Object.<anonymous> (/Users/feenr/workspaces/mean/server/config/config.js:30:9)
[SERVER]     at Module._compile (module.js:652:30)
[SERVER]     at Object.Module._extensions..js (module.js:663:10)
[SERVER]     at Module.load (module.js:565:32)
[SERVER]     at tryModuleLoad (module.js:505:12)
[SERVER]     at Function.Module._load (module.js:497:3)
[SERVER]     at Module.require (module.js:596:17)
[SERVER]     at require (internal/module.js:11:18)
[SERVER]     at Object.<anonymous> (/Users/feenr/workspaces/mean/server/index.js:2:16)
[SERVER]     at Module._compile (module.js:652:30)
[SERVER] [nodemon] app crashed - waiting for file changes before starting...
[BUILD] Cannot destructure property `createHash` of 'undefined' or 'null'.
[BUILD] TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.
[BUILD]     at Object.<anonymous> (/Users/feenr/workspaces/mean/node_modules/mini-css-extract-plugin/dist/index.js:21:5)
[BUILD]     at Module._compile (module.js:652:30)
[BUILD]     at Object.Module._extensions..js (module.js:663:10)
[BUILD]     at Module.load (module.js:565:32)
[BUILD]     at tryModuleLoad (module.js:505:12)
[BUILD]     at Function.Module._load (module.js:497:3)
[BUILD]     at Module.require (module.js:596:17)
[BUILD]     at require (internal/module.js:11:18)
[BUILD]     at Object.<anonymous> (/Users/feenr/workspaces/mean/node_modules/mini-css-extract-plugin/dist/cjs.js:3:18)
[BUILD]     at Module._compile (module.js:652:30)
[BUILD]     at Object.Module._extensions..js (module.js:663:10)
[BUILD]     at Module.load (module.js:565:32)
[BUILD]     at tryModuleLoad (module.js:505:12)
[BUILD]     at Function.Module._load (module.js:497:3)
[BUILD]     at Module.require (module.js:596:17)
[BUILD]     at require (internal/module.js:11:18)
[BUILD] ng build --watch exited with code 1
[SERVER] nodemon server exited with code 130
```

**Comment by feenr** [comment] 2018-10-07 16:09
My comment had two seperate errors. The first is easily fixed by copying the environment file. There was a minor typo in the readme.
```env-example``` should be ```.env-example```

**Comment by feenr** [comment] 2018-10-07 16:17
I noticed that this project doesn't have a package.lock committed to the repository. I suspect this is roughly the root cause of the build error. I manually installed webpack, which was a missing depedency. However, I now see a different error.

If a project owner has a functioning workspace it might be helpful to commit the package.lock file.

**Comment by Guillerbr** [comment] 2018-10-07 16:46
ok

**Comment by feenr** [comment] 2018-10-07 18:49
Ah okay. I have never used yarn. Following the new set of instructions I still get an error:
```Unknown error: Error: schema with key or id "http://json-schema.org/draft-06/schema" already exists```

**Comment by feenr** [comment] 2018-10-07 18:56
Removed node_modules folder and performed install again, which fixed that error.

**Comment by rachelbruk** [comment] 2018-10-07 20:17
Remove node_modules and start again.
Worked for.me.
Lior

**Comment by responsivedevelopment** [comment] 2018-10-09 23:46
yarn start
yarn run v1.10.1
$ concurrently -c 'yellow.bold,green.bold' -n 'SERVER,BUILD' 'nodemon server' 'ng build --watch'
['SERVER] 'nodemo' is not recognized as an internal or external command,
['SERVER] operable program or batch file.
[BUILD'] 'server'' is not recognized as an internal or external command,
[BUILD'] operable program or batch file.
[2] 'n' is not recognized as an internal or external command,
[2] operable program or batch file.
[3] 'build' is not recognized as an internal or external command,
[3] operable program or batch file.
[3] build exited with code 1
[2] n exited with code 1
[BUILD'] server' exited with code 1
['SERVER] nodemo exited with code 1
error Command failed with exit code 1.

**Comment by feenr** [comment] 2018-10-10 03:11
Another user reported the same issue:
https://github.com/linnovate/mean/issues/1909

**Comment by liorkesos** [comment] 2018-10-31 06:28
@renceabishek please see if the problem persists (I'd start from a clean slate and follow the readme)

**Comment by alphapilgrim** [comment] 2018-11-21 16:58
@liorkesos I started from a clean slate as you suggested, but now I get a different error.

`/mean/node_modules/mongodb/lib/mongo_client.js:794
[SERVER]           throw err;
[SERVER]           ^
[SERVER]
[SERVER] Error: unable to connect to database: mongodb://localhost/mean
[SERVER]     at NativeConnection.mongoose.connection.on (/Projects/mean/server/config/mongoose.js:11:9)
[SERVER]     at emitOne (events.js:116:13)
[SERVER]     at NativeConnection.emit (events.js:211:7)
[SERVER]     at /Projects/mean/node_modules/mongoose/lib/connection.js:440:17
[SERVER]     at err (/Projects/mean/node_modules/mongodb/lib/utils.js:415:14)
[SERVER]     at executeCallback (/Projects/mean/node_modules/mongodb/lib/utils.js:404:25)
[SERVER]     at /Projects/mean/node_modules/mongodb/lib/mongo_client.js:271:21
[SERVER]     at connectCallback (/Projects/mean/node_modules/mongodb/lib/mongo_client.js:946:5)
[SERVER]     at /Projects/mean/node_modules/mongodb/lib/mongo_client.js:791:11
[SERVER]     at _combinedTickCallback (internal/process/next_tick.js:131:7)
[SERVER]     at process._tickCallback (internal/process/next_tick.js:180:9)
[SERVER] [nodemon] app crashed - waiting for file changes before starting...`

**Comment by avitalarusi** [comment] 2018-11-21 18:00
What node/mongo/operating system combination?

**Comment by alphapilgrim** [comment] 2018-11-27 15:31
@avitalarusi the lastest, I just cloned this repo that day. @feenr I agree if someone is coming from a non-DB background starting the service should be mentioned in the readme.

**Comment by feenr** [comment] 2018-11-27 16:54
Did starting mongo help with your issue?

**Comment by alphapilgrim** [comment] 2018-11-27 20:12
@feenr will try this later tonight, will update.

**Comment by liorkesos** [comment] 2018-12-02 07:39
I fixed the repo and docs back to using npm

**Closed by liorkesos** 2018-12-02 07:39 UTC
