### ISSUE TITLE
StackSight Error : apiKey not supplied 

### ISSUE THREAD

**Issue by subramaniamarun** [linnovate/mean#1600] opened 2016-06-26 07:45 UTC
I am facing this error in MEAN branch 0.5.5, after executing the gulp command. See logs :

C:\MEAN_Stack\myMeanNewTest>gulp
Invoking gulp - development
[02:56:34] Using gulpfile C:\MEAN_Stack\myMeanNewTest\gulpfile.js
[02:56:34] Starting 'clean'...
[02:56:34] Finished 'clean' after 13 ms
[02:56:34] Starting 'default'...
[02:56:34] Starting 'coffee'...
[02:56:34] Finished 'coffee' after 24 ms
[02:56:34] Starting 'clean'...
[02:56:34] Starting 'less'...
[02:56:34] Starting 'csslint'...
[02:56:34] Starting 'env:development'...
[02:56:34] Finished 'env:development' after 54 µs
[02:56:34] Starting 'devServe'...
[02:56:34] Finished 'devServe' after 105 ms
[02:56:34] Starting 'watch'...
[02:56:48] Finished 'watch' after 14 s
[02:56:48] Finished 'clean' after 15 s
[02:56:50] [nodemon] 1.9.2
[02:56:50] [nodemon] to restart at any time, enter `rs`
[02:56:50] [nodemon] watching: _._
[02:56:50] [nodemon] starting `node --debug server.js`
Debugger listening on port 5858
 undefined

**C:\MEAN_Stack\myMeanNewTest\node_modules\mongoose\node_modules\mongodb\lib\server.js:309
      process.nextTick(function() { throw err; })
                                    ^
 StackSight Error: apiKey not supplied**
 [02:56:52] [nodemon] app crashed - waiting for file changes before starting...
[02:56:54] csslint: 3 files lint free
[02:56:54] Finished 'csslint' after 20 s
[02:56:54] Finished 'less' after 20 s
[02:56:54] Starting 'development'...
[02:56:54] Finished 'development' after 7.93 µs

**Comment by quentinhayot** [comment] 2016-06-27 15:09
Same issue here. I just updated mean, never heard of StackSight before :(

**Comment by liorkesos** [comment] 2016-06-27 15:49
Well look in to it stacksight is a dependency we had which we tries to
remove. I guess the pr merges has some edge cases.
Well look at it asap..
Lior

**Comment by quentinhayot** [comment] 2016-06-27 15:50
I managed to get rid of the error by commenting out the StackSight dependency in node_modules/meanio/package.json:
```
"dependencies": {
   ...
    //"stacksight": "latest",
...
  },
```

**Comment by VikramTiwari** [comment] 2016-06-28 16:59
@liorkesos Stacksight is breaking even older builds. I am on 0.5.5 and its broken cause of that, even without updating to latest dependencies.

**Comment by liorkesos** [comment] 2016-06-28 17:21
Which version of meanio package are you running?
Please send the output of npm ls meanio
Lior

**Comment by VikramTiwari** [comment] 2016-06-28 17:27
```
mean@0.5.5 /Users/Vikram/Documents/code/project-abc
└── meanio@0.8.83  (git://github.com/linnovate/meanio.git#b3ecdc85a8d9714552da1e4bfd549569b77dcf33)
```

**Comment by rivkabenshalom** [comment] 2016-06-30 07:36
you  have install stacksight latest

**Comment by johndshea** [comment] 2016-07-05 14:50
I'm having the same issue running meanio 0.8.84. Installing stacksight latest did not help.

**Comment by liorkesos** [comment] 2016-07-05 16:31
@rivkabenshalom The idea here is not how to work with Stacksight, the whole issue arose when the PR was merged to remove stacksight. (thats the first time stacksight has ever affected meanio)
The challange is how to remove stacksight and let people that are still on 0.5.5x work without stacksight if they wish.
Diving in...

**Comment by liorkesos** [comment] 2016-07-05 16:55
I think I fixed it.
Please reclone the -0.5.5 branch and try again

**Comment by quentinhayot** [comment] 2016-07-08 14:54
Looks like patching master with a303f897f5a39395b716ea9137d5745853b1f7ad works too.

**Comment by johndshea** [comment] 2016-07-08 15:31
thanks, @liorkesos !

**Comment by clowenhg** [comment] 2016-07-10 21:00
@quentinhayot The issue is that there was a change in StackSight that caused it to throw errors. The errors were resulting because Meanio 0.8.84 (Mean 0.5.5) was still using StackSight.  Meanio 0.9.x (Mean 0.6.x) already had an update to remove StackSight from Meanio.

I applied the same removal from Meanio 0.9 to Meanio 0.8.85.  Mean 0.5.5 has an npm shrinkwrap which forces a Meanio version. So removing the shrinkwrap and doing an update or fresh install would pull the latest Meanio ^0.8 which is no 0.8.85 with the StackSight fix.

**Comment by saeed68gm** [comment] 2017-06-04 16:45
facing this issue after installing passport-facebook-token. No idea why this should arise but the solutions discussed here did not help. Any suggestions? @liorkesos

**Closed** 2017-09-29 03:44 UTC
Labels: bug

**Comment by saeed68gm** [comment] 2017-09-29 05:19
@liorkesos what was the solution? I had to manually throw stuff out to get it working

**Comment by liorkesos** [comment] 2017-09-30 16:59
We've made a big change with mean2 - this issue is no longer rellevent . Trying to clean up , focus and double down around the new framework (angular 4, Graphql, universal support etc...)
